

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"  # Map backend container port to host port
    volumes: 
      - ./backend:/app 
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=mysql://root:rootpassword@db:3308/musicdb
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"  # Map frontend container port to host port
    networks:
      - app-network
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000  # Set backend API URL for React

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: musicdb
    ports:
      - "3308:3306"  # Expose MySQL port (not recommended for production)
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql  # Persist MySQL data

volumes:
  db_data:
    driver: local

networks:
  app-network:
    driver: bridge
